[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "fast-module"
version = "0.1.0"

[tool.scikit-build]
cmake.source-dir = "."
cmake.build-type = "Release"

if(FALSE)
[tool.scikit-build.cmake.define]
CMAKE_CXX_COMPILER = "cl"
endif()